### ISSUE TITLE
vRA8 Custom Provisioning: Part One - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#7]
# vRA8 Custom Provisioning: Part One - Virtually Potato

I recently shared some details about my little self-contained VMware homelab as well as how I integrated {php}IPAM into vRealize Automation 8 for assigning IPs to deployed VMs. For my next trick, I’ll be crafting a flexible Cloud Template and accompanying vRealize Orchestrator workflow that will help to deploy and configure virtual machines based on a vRA user’s input. Buckle up, this is going to be A Ride.

[https://virtuallypotato.com/vra8-custom-provisioning-part-one](https://virtuallypotato.com/vra8-custom-provisioning-part-one)

**Comment by vimwtf** [comment]
**Dennis**
*Posted June 12, 2021 on [Hashnode](https://hash.virtuallypotato.com/vra8-custom-provisioning-part-one#ckpulic5g04470ms1gw07asv4)*

Fantastic series you are writing - a big THANK YOU for putting this all together and also focusing on Windows. This is a big problem I see where most of the blogs are all about Linux while most Enterprises need to automate Windows Server in a big way.

I have been also trying to bend vRA 8.x to my will and have something I hope you will find useful:

Using an array in the input form to select an OS can also be used to bind the Customisation spec to the machine resource (I suppose you are usinging cust spec and not cloud(base)-init?).

Here's a snippet which I use:

```yaml
inputs:
  operatingSystem:
    type: string
    # Set the values below as 'image name,customisation spec'
    oneOf:
      - title: Microsoft Windows Server 2019
        const: 'windows-server-2019,windows-spec-noad'
      - title: CentOS Server 7.9
        const: 'centos-79,linux-spec'
      - title: CentOS Server 8.3
        const: 'centos-83,linux-spec'
resources:
  Cloud_vSphere_Machine_1:
    type: Cloud.vSphere.Machine
    properties:
        image: '${split(input.operatingSystem,",")[0]}'
        customizationSpec: '${split(input.operatingSystem,",")[1]}'
```
