### ISSUE TITLE
Adding VM Notes and Custom Attributes with vRA8 - Virtually Potato

### ISSUE THREAD

**Issue by utterances-bot** [vimwtf/site-comments#8]
# Adding VM Notes and Custom Attributes with vRA8 - Virtually Potato

In past posts, I started by creating a basic deployment infrastructure in Cloud Assembly and using tags to group those resources. I then wrote an integration to let vRA8 use phpIPAM for static address assignments. I implemented a vRO workflow for generating unique VM names which fit an organization’s established naming standard, and then extended the workflow to avoid any naming conflicts in Active Directory and DNS. And, finally, I created an intelligent provisioning request form in Service Broker to make it easy for users to get the servers they need. That’s got the core functionality pretty well sorted, so moving forward I’ll be detailing additions that enable new capabilities and enhance the experience.

[https://virtuallypotato.com/adding-vm-notes-and-custom-attributes-with-vra8](https://virtuallypotato.com/adding-vm-notes-and-custom-attributes-with-vra8)

**Comment by vimwtf** [comment]
**Dennis**
*Posted June 12, 2021 on [Hashnode](https://hash.virtuallypotato.com/adding-vm-notes-and-custom-attributes-with-vra8#ckpulsm6s03yfzls1bxb69nl8)*

I also found useful the ability to add vCenter tags in the blueprint which can be used by vRO and vRNI for application mapping, reporting etc. You can update the tag values from selections in an input form.

```yaml
  Cloud_vSphere_Machine_1:
    properties:
      tags:
        - key: Application
          value: MyApp1
        ### Update environment name from Input e.g. Dev, Staging, Prod
        - key: Environment
          value: Prod
        ### Update tenant name from Input
        - key: Tenant
          value: T98
```
